[tool.poetry]
name = "fastembed"
version = "0.1.2"
description = "Fast, light, accurate library built for retrieval embedding generation"
authors = ["NirantK <nirant.bits@gmail.com>"]
license = "Apache License"
readme = "README.md"
packages = [{include = "fastembed"}]
homepage = "https://github.com/qdrant/fastembed"
repository = "https://github.com/qdrant/fastembed"
keywords = ["vector", "embedding", "neural", "search", "qdrant", "sentence-transformers"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.12"
onnx = "^1.11"
onnxruntime = "^1.15"
tqdm = "^4.65"
requests = "^2.31"
tokenizers = "^0.15.0"
huggingface-hub = "0.19.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
ruff = "^0.1.13"
notebook = ">=7.0.2"
mkdocs-material = "^9.1.21"
mkdocstrings = "^0.22.0"
pillow = "^10.0.0"
cairosvg = "^2.7.1"
mknotebooks = "^0.8.0"
pre-commit = { version = "^3.6.0", python = ">=3.9,<3.12" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
